import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router';
import { Award, Car, Check, MapPin, Pencil, Plus, Save, Star, Trash2, User, X } from 'lucide-react';
import { motion } from 'motion/react';
import { useAuth } from '../context/AuthContext';
import { clearSignupProfilePending } from '../lib/signupProfileGate';
import {
  apiGetCustomerMe,
  apiListAddresses,
  apiCreateAddress,
  apiUpdateAddress,
  apiDeleteAddress,
  apiSetDefaultAddress,
  apiRequestEmailChange,
  apiVerifyEmailChange,
  apiRequestPhoneChange,
  apiVerifyPhoneChange,
  FieldValidationError,
  type SavedAddress,
} from '../lib/userApi';
import { useAdminBridgeSync } from '../hooks/useAdminBridgeSync';
import { listAllBookableVehicleTypes } from '../lib/adminPortalBridge';
import { AddressDetailsFields } from '../components/AddressDetailsFields';
import { createEmptyAddressDetails } from '../lib/addressDetails';
import { HEADING_FONT_FAMILY } from '../lib/branding';

interface Vehicle { id: string; type: string; number: string; model: string }

/* ── palette ── */
const NAVY      = '#0c1d3a';
const NAVY_MID  = '#1a3560';
const NAVY_TINT = '#e8eef8';  // very light blue for icon containers / hover
const GOLD      = '#c9a84c';
const BTN_BG    = '#c9a84c';
const BTN_TEXT  = '#0c1d3a';

const inp =
  'w-full px-4 py-3 border rounded-xl text-sm outline-none transition-all text-gray-900 placeholder:text-gray-400 placeholder:font-normal focus:ring-2 focus:border-transparent';

/* navy focus ring via CSS var trick */
const inpFocus = { '--tw-ring-color': NAVY } as React.CSSProperties;

/* ── Section card ── */
function Section({
  icon: Icon, title, badge, children,
}: {
  icon?: React.ElementType; title: string; badge?: string; children: React.ReactNode;
}) {
  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
      <div
        className="px-6 py-4 flex items-center gap-3 border-b border-gray-100"
        style={{ borderLeftWidth: 4, borderLeftColor: NAVY, borderLeftStyle: 'solid' }}
      >
        {Icon && (
          <span
            className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
            style={{ background: NAVY_TINT }}
          >
            <Icon className="w-4 h-4" style={{ color: NAVY }} />
          </span>
        )}
        <h2 className="font-semibold text-gray-900" style={{ fontFamily: HEADING_FONT_FAMILY, color: NAVY }}>
          {title}
        </h2>
        {badge && (
          <span
            className="ml-auto text-xs font-medium px-2.5 py-0.5 rounded-full"
            style={{ background: NAVY_TINT, color: NAVY_MID }}
          >
            {badge}
          </span>
        )}
      </div>
      <div className="px-6 py-6">{children}</div>
    </div>
  );
}

/* ── Form field label row ── */
function FieldLabel({
  label, required: isRequired, autoGenerated,
}: {
  label: string; required?: boolean; autoGenerated?: boolean;
}) {
  return (
    <label className="block text-sm font-medium text-gray-700 mb-1.5">
      {label}
      {isRequired && <span className="text-red-500 ml-0.5">*</span>}
      {!isRequired && !autoGenerated && (
        <span className="text-gray-400 text-xs ml-1.5 font-normal">(Optional)</span>
      )}
    </label>
  );
}

export function ProfileSetup() {
  const navigate = useNavigate();
  const { hasCustomerSession, session, updateCustomerProfile } = useAuth();
  const [name, setName]           = useState('');
  const [email, setEmail]         = useState('');
  const [originalEmail, setOriginalEmail] = useState('');
  const [memberId, setMemberId]   = useState('');
  const [phone, setPhone]         = useState('');
  const [originalPhone, setOriginalPhone] = useState('');
  const [vehicles, setVehicles]   = useState<Vehicle[]>([]);

  // ── Email change OTP ──────────────────────────────────────────────────────
  type EmailOtpState = {
    step: 'idle' | 'sending' | 'sent' | 'verifying' | 'verified';
    code: string;
    error: string;
  };
  const [emailOtp, setEmailOtp] = useState<EmailOtpState>({ step: 'idle', code: '', error: '' });
  // Signed JWT returned by verify-email-change — passed to PATCH so the backend
  // can verify it without shared in-memory state (works across multiple workers).
  const [emailChangeToken, setEmailChangeToken] = useState<string | null>(null);
  const [phoneOtp, setPhoneOtp] = useState<EmailOtpState>({ step: 'idle', code: '', error: '' });
  const [phoneChangeToken, setPhoneChangeToken] = useState<string | null>(null);

  // Multi-address state
  const [addresses, setAddresses] = useState<SavedAddress[]>([]);
  const [addrFormOpen, setAddrFormOpen] = useState(false);
  const [addrEditId, setAddrEditId] = useState<string | null>(null);
  const [addrDraft, setAddrDraft] = useState(createEmptyAddressDetails());
  const [addrLabel, setAddrLabel] = useState('Home');
  const [addrSaving, setAddrSaving] = useState(false);
  const [addrError, setAddrError] = useState('');
  const [currentVehicle, setCurrentVehicle] = useState({ type: '', number: '', model: '' });
  const [error, setError]             = useState('');
  const [serverFieldErrors, setServerFieldErrors] = useState<Record<string, string>>({});
  const [loading, setLoading]         = useState(false);
  const [hydrated, setHydrated]       = useState(false);
  const [submitAttempted, setSubmitAttempted] = useState(false);
  const [saved, setSaved]             = useState(false);
  const [vehicleFormOpen, setVehicleFormOpen] = useState(false);
  const [vehicleEditId, setVehicleEditId] = useState<string | null>(null);
  const [vehicleAddTouched, setVehicleAddTouched] = useState(false);

  const catalogSync = useAdminBridgeSync(15000);
  /** Admin-configured branch + mobile vehicle types only (no legacy profile merges). */
  const vehicleCatalogTypes = useMemo(
    () => listAllBookableVehicleTypes(),
    [catalogSync],
  );

  const getErrors = () => {
    const errs: Record<string, string> = {};
    const nameRegex = /^[a-zA-Z\s-]+$/;
    if (!name) errs.name = 'Full name is required';
    else if (name.trim().length < 2) errs.name = 'Must be at least 2 characters';
    else if (!nameRegex.test(name)) errs.name = 'Letters and spaces only';
    if (email && !/\S+@\S+\.\S+/.test(email)) errs.email = 'Enter a valid email address';
    if (!phone) errs.phone = 'Phone number is required';
    else if (!/^4\d{8}$/.test(phone.replace(/\s/g, '')))
      errs.phone = 'Enter the remaining 9 digits of your Australian mobile';
    return errs;
  };

  const fieldErrors = getErrors();

  useEffect(() => {
    if (!hasCustomerSession) navigate('/login', { replace: true });
  }, [hasCustomerSession, navigate]);

  useEffect(() => {
    if (!session?.accessToken) return;
    // Clear any stale guest vehicle draft that may be lingering in localStorage.
    localStorage.removeItem('guestVehicle');
    let cancelled = false;
    (async () => {
      try {
        // Always fetch fresh profile data from the backend — the database is the
        // source of truth for vehicles, not the session cache.
        const [me, addrRes] = await Promise.all([
          apiGetCustomerMe(session.accessToken),
          apiListAddresses(session.accessToken).catch(() => ({ addresses: [] as typeof addresses })),
        ]);
        if (cancelled) return;
        if (me.id) setMemberId(me.id);
        setEmail(me.email ?? '');
        setOriginalEmail(me.email ?? '');
        if (me.full_name) setName(me.full_name);
        if (me.phone) {
          const localPhone = me.phone.replace('+61', '').replace(/^0/, '');
          setPhone(localPhone);
          setOriginalPhone(`+61${localPhone}`);
        }
        // Vehicles always come from the API response, never from session/localStorage.
        setVehicles((me.vehicles ?? []).map((v: any, i: number) => ({
          id: `v-${i}-${v.number ?? i}`,
          type: v.type ?? '',
          number: v.number ?? '',
          model: v.model ?? '',
        })));
        setAddresses(addrRes.addresses);
      } catch {
        if (!cancelled) setEmail(session?.email ?? '');
      } finally {
        if (!cancelled) setHydrated(true);
      }
    })();
    return () => { cancelled = true; };
  // accessToken is stable for the lifetime of a session; email is only here as a safety net.
  }, [session?.accessToken, session?.email]);

  const saveVehicle = () => {
    const modelTrim = currentVehicle.model.trim();
    if (currentVehicle.type && currentVehicle.number && modelTrim) {
      if (vehicleEditId) {
        setVehicles(prev => prev.map(v =>
          v.id === vehicleEditId
            ? { ...v, type: currentVehicle.type, number: currentVehicle.number, model: modelTrim }
            : v,
        ));
      } else {
        setVehicles(prev => [...prev, {
          id: Date.now().toString(),
          type: currentVehicle.type, number: currentVehicle.number, model: modelTrim,
        }]);
      }
      closeVehicleForm();
      return true;
    }
    return false;
  };

  const closeVehicleForm = () => {
    setVehicleFormOpen(false);
    setVehicleAddTouched(false);
    setVehicleEditId(null);
    setCurrentVehicle({ type: '', number: '', model: '' });
  };

  const startEditVehicle = (vehicle: Vehicle) => {
    setVehicleEditId(vehicle.id);
    setCurrentVehicle({ type: vehicle.type, number: vehicle.number, model: vehicle.model });
    setVehicleFormOpen(true);
    setVehicleAddTouched(false);
  };

  const handleSaveVehicleClick = () => {
    if (!saveVehicle()) setVehicleAddTouched(true);
  };

  const removeVehicle = (id: string) => {
    setVehicles(prev => prev.filter(v => v.id !== id));
    if (vehicleEditId === id) closeVehicleForm();
  };

  const isEmailChanging = email.trim().toLowerCase() !== originalEmail.trim().toLowerCase();
  const emailChangeVerified = emailOtp.step === 'verified';
  const fullPhone = `+61${phone.trim()}`;
  const isPhoneChanging = fullPhone !== originalPhone.trim();
  const phoneChangeVerified = phoneOtp.step === 'verified';

  // Send OTP to the new email address.
  const handleSendEmailChangeOtp = async () => {
    if (!session?.accessToken) return;
    setEmailOtp(p => ({ ...p, step: 'sending', error: '' }));
    try {
      await apiRequestEmailChange(session.accessToken, email.trim().toLowerCase());
      setEmailOtp(p => ({ ...p, step: 'sent', error: '' }));
    } catch (err) {
      setEmailOtp(p => ({ ...p, step: 'idle', error: err instanceof Error ? err.message : 'Could not send code.' }));
    }
  };

  // Verify the OTP entered by the user.
  const handleVerifyEmailChangeOtp = async () => {
    if (!session?.accessToken) return;
    setEmailOtp(p => ({ ...p, step: 'verifying', error: '' }));
    try {
      const result = await apiVerifyEmailChange(session.accessToken, email.trim().toLowerCase(), emailOtp.code);
      // Store the signed verification token — it's passed to the PATCH so the
      // backend can verify the email change without relying on shared in-memory state.
      setEmailChangeToken(result.email_change_token);
      setEmailOtp(p => ({ ...p, step: 'verified', error: '' }));
    } catch (err) {
      setEmailOtp(p => ({ ...p, step: 'sent', error: err instanceof Error ? err.message : 'Invalid code.' }));
    }
  };

  const handleSendPhoneChangeOtp = async () => {
    if (!session?.accessToken) return;
    setPhoneOtp(p => ({ ...p, step: 'sending', error: '' }));
    try {
      await apiRequestPhoneChange(session.accessToken, fullPhone);
      setPhoneOtp(p => ({ ...p, step: 'sent', error: '' }));
    } catch (err) {
      setPhoneOtp(p => ({ ...p, step: 'idle', error: err instanceof Error ? err.message : 'Could not send code.' }));
    }
  };

  const handleVerifyPhoneChangeOtp = async () => {
    if (!session?.accessToken) return;
    setPhoneOtp(p => ({ ...p, step: 'verifying', error: '' }));
    try {
      const result = await apiVerifyPhoneChange(session.accessToken, fullPhone, phoneOtp.code);
      setPhoneChangeToken(result.phone_change_token);
      setPhoneOtp(p => ({ ...p, step: 'verified', error: '' }));
    } catch (err) {
      setPhoneOtp(p => ({ ...p, step: 'sent', error: err instanceof Error ? err.message : 'Invalid code.' }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setServerFieldErrors({});
    setSubmitAttempted(true);
    const errorsList = Object.values(fieldErrors);
    if (errorsList.length > 0) {
      setError(`Please complete the following: ${errorsList.join(', ')}`);
      return;
    }
    // If the email was changed, require OTP verification first.
    if (isEmailChanging && email.trim() && !emailChangeVerified) {
      if (emailOtp.step === 'idle') {
        await handleSendEmailChangeOtp();
      }
      return;
    }
    if (isPhoneChanging && !phoneChangeVerified) {
      if (phoneOtp.step === 'idle') {
        await handleSendPhoneChangeOtp();
      }
      return;
    }
    setLoading(true);
    try {
      const modelDraft = currentVehicle.model.trim();
      const numberOk = !!currentVehicle.number && /^[A-Z0-9]{2,7}$/.test(currentVehicle.number);
      const draftComplete = vehicleFormOpen && !!currentVehicle.type && numberOk && !!modelDraft;
      const vehiclesPayload = vehicles.map(v => {
        if (vehicleEditId && v.id === vehicleEditId && draftComplete) {
          return { type: currentVehicle.type, number: currentVehicle.number, model: modelDraft };
        }
        return { type: v.type, number: v.number, model: v.model };
      });
      if (draftComplete && !vehicleEditId) {
        vehiclesPayload.push({ type: currentVehicle.type, number: currentVehicle.number, model: modelDraft });
      }
      await updateCustomerProfile({
        full_name: name.trim(),
        phone: fullPhone,
        address: '',
        email: email.trim().toLowerCase(),
        vehicles: vehiclesPayload,
        // Include the signed token when the email was changed so the backend can
        // verify across multiple workers without shared in-memory OTP state.
        ...(emailChangeToken ? { email_change_token: emailChangeToken } : {}),
        ...(phoneChangeToken ? { phone_change_token: phoneChangeToken } : {}),
      });
      clearSignupProfilePending();
      // Reflect new email as the baseline so the OTP gate won't re-trigger.
      setOriginalEmail(email.trim().toLowerCase());
      setOriginalPhone(fullPhone);
      setEmailOtp({ step: 'idle', code: '', error: '' });
      setEmailChangeToken(null);
      setPhoneOtp({ step: 'idle', code: '', error: '' });
      setPhoneChangeToken(null);
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch (err) {
      if (err instanceof FieldValidationError) {
        // Show each field error under its own input — reset email OTP state
        // if the backend rejected the email field so the user can re-verify.
        setServerFieldErrors(err.fields);
        if (err.fields.email) {
          setEmailOtp({ step: 'idle', code: '', error: '' });
          setEmailChangeToken(null);
        }
        if (err.fields.phone) {
          setPhoneOtp({ step: 'idle', code: '', error: '' });
          setPhoneChangeToken(null);
        }
      } else {
        setError(err instanceof Error ? err.message : 'Could not save profile. Please try again.');
      }
    } finally { setLoading(false); }
  };

  if (!hasCustomerSession) return null;

  return (
    <div className="min-h-screen" style={{ background: '#eef3fa' }}>
      {/* gold accent bar – consistent with auth page */}
      <div className="h-0.5 w-full" style={{ background: `linear-gradient(90deg, ${GOLD} 0%, #e8c97a 50%, transparent 100%)` }} />

      <div className="max-w-3xl mx-auto px-4 py-8">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, ease: 'easeOut' }}>

          {/* ── page header ── */}
          <div className="mb-8">
            <h1
              className="text-2xl font-bold"
              style={{ fontFamily: HEADING_FONT_FAMILY, color: NAVY }}
            >
              {session?.profileCompleted ? 'Your Profile' : 'Set Up Your Profile'}
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              {session?.profileCompleted
                ? 'Keep your contact details and vehicles up to date for a seamless booking experience.'
                : 'Complete your profile to personalise your experience and speed up future bookings.'}
            </p>

            {/* ── loyalty rewards banner ── */}
            <div
              className="mt-5 rounded-2xl overflow-hidden"
              style={{ background: NAVY, boxShadow: `0 4px 20px rgba(12,29,58,0.15)` }}
            >
              <div className="px-5 py-4 flex items-start gap-4">
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 mt-0.5"
                  style={{ background: 'rgba(201,168,76,0.2)' }}
                >
                  <Award className="w-5 h-5" style={{ color: GOLD }} />
                </div>
                <div className="flex-1">
                  <p
                    className="text-sm font-semibold mb-1"
                    style={{ color: GOLD, fontFamily: HEADING_FONT_FAMILY }}
                  >
                    Loyalty Rewards Programme
                  </p>
                  <p className="text-xs leading-relaxed" style={{ color: 'rgba(255,255,255,0.7)' }}>
                    Earn points on every eligible wash and unlock exclusive member perks.
                    Adding your mobile number and email ensures your visits are tracked automatically.
                  </p>
                </div>
              </div>
              {/* gold accent line */}
              <div className="h-px" style={{ background: `linear-gradient(90deg, ${GOLD} 0%, transparent 80%)` }} />
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-5">

            {/* ── Personal Details ── */}
            <Section icon={User} title="Personal Details">
              <div className="space-y-5">

                {/* Full Name */}
                <div>
                  <FieldLabel label="Full Name" required />
                  <input
                    type="text"
                    value={name}
                    onChange={e => { const v = e.target.value; if (v === '' || /^[a-zA-Z\s-]*$/.test(v)) setName(v); }}
                    placeholder="e.g. Jane Doe"
                    style={inpFocus}
                    className={`${inp} ${submitAttempted && fieldErrors.name ? 'border-red-400 bg-red-50' : 'border-gray-300 hover:border-gray-400'}`}
                  />
                  {submitAttempted && fieldErrors.name && <p className="text-xs text-red-500 mt-1.5">{fieldErrors.name}</p>}
                </div>

                {/* Member ID */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1.5">Member ID</label>
                  <div className="relative">
                    <input
                      type="text"
                      value={memberId}
                      readOnly
                      className="w-full px-4 py-3 border border-gray-200 rounded-xl text-sm bg-gray-50 text-gray-500 outline-none font-mono tracking-wide pr-28"
                    />
                    <span
                      className="absolute right-3 top-1/2 -translate-y-1/2 text-xs font-medium px-2 py-0.5 rounded-full"
                      style={{ background: NAVY_TINT, color: NAVY_MID }}
                    >
                      Auto-generated
                    </span>
                  </div>
                  <p className="text-xs text-gray-400 mt-1.5"></p>
                </div>

                {/* Email */}
                <div>
                  <FieldLabel label="Email Address" />
                  <input
                    type="email"
                    value={email}
                    onChange={e => {
                      setEmail(e.target.value);
                      // Reset OTP state and any stale verification token when the email field is edited.
                      setEmailOtp({ step: 'idle', code: '', error: '' });
                      setEmailChangeToken(null);
                      if (serverFieldErrors.email) setServerFieldErrors(p => ({ ...p, email: undefined as any }));
                    }}
                    autoComplete="email"
                    placeholder="e.g. you@example.com"
                    style={inpFocus}
                    className={`${inp} ${submitAttempted && fieldErrors.email ? 'border-red-400 bg-red-50' : 'border-gray-300 hover:border-gray-400'}`}
                  />
                  {submitAttempted && fieldErrors.email && <p className="text-xs text-red-500 mt-1.5">{fieldErrors.email}</p>}
                  {serverFieldErrors.email && <p className="text-xs text-red-500 mt-1.5">{serverFieldErrors.email}</p>}

                  {/* Email change OTP panel — shown only when the email has been edited */}
                  {isEmailChanging && !!email.trim() && (
                    <div className="mt-3 rounded-xl border border-amber-200 bg-amber-50/60 p-4 space-y-3">
                      {emailOtp.step === 'idle' && (
                        <>
                          <p className="text-xs text-amber-800 leading-relaxed">
                            You've changed your email address. To keep your account secure, we'll send a verification code to <strong>{email.trim()}</strong> before saving.
                          </p>
                          <button
                            type="button"
                            onClick={() => void handleSendEmailChangeOtp()}
                            className="rounded-lg px-3 py-2 text-xs font-semibold transition-all"
                            style={{ background: GOLD, color: NAVY }}
                          >
                            Send verification code
                          </button>
                          {emailOtp.error && <p className="text-xs text-red-600">{emailOtp.error}</p>}
                        </>
                      )}

                      {emailOtp.step === 'sending' && (
                        <p className="text-xs text-amber-700">Sending code…</p>
                      )}

                      {(emailOtp.step === 'sent' || emailOtp.step === 'verifying') && (
                        <>
                          <p className="text-xs text-amber-800">
                            Code sent to <strong>{email.trim()}</strong>. Enter it below to verify your new email.
                          </p>
                          <input
                            type="text"
                            inputMode="numeric"
                            maxLength={6}
                            value={emailOtp.code}
                            onChange={e => setEmailOtp(p => ({ ...p, code: e.target.value.replace(/\D/g, '') }))}
                            placeholder="000000"
                            className="w-full px-4 py-2.5 border border-amber-300 rounded-lg text-center text-lg font-mono tracking-[0.5em] outline-none focus:ring-2 bg-white"
                            style={{ '--tw-ring-color': GOLD } as React.CSSProperties}
                          />
                          {emailOtp.error && <p className="text-xs text-red-600">{emailOtp.error}</p>}
                          <div className="flex gap-2">
                            <button
                              type="button"
                              disabled={emailOtp.code.length !== 6 || emailOtp.step === 'verifying'}
                              onClick={() => void handleVerifyEmailChangeOtp()}
                              className="rounded-lg px-3 py-2 text-xs font-semibold transition-all disabled:opacity-60"
                              style={{ background: NAVY, color: '#fff' }}
                            >
                              {emailOtp.step === 'verifying' ? 'Verifying…' : 'Verify code'}
                            </button>
                            <button
                              type="button"
                              disabled={emailOtp.step === 'verifying'}
                              onClick={() => void handleSendEmailChangeOtp()}
                              className="rounded-lg px-3 py-2 text-xs font-medium text-amber-700 transition-all hover:underline disabled:opacity-50"
                            >
                              Resend
                            </button>
                          </div>
                        </>
                      )}

                      {emailOtp.step === 'verified' && (
                        <p className="text-xs font-medium" style={{ color: '#059669' }}>
                          ✓ New email verified — your address will be updated when you save.
                        </p>
                      )}
                    </div>
                  )}
                </div>

                {/* Phone */}
                <div>
                  <FieldLabel label="Mobile Number" required />
                  <div className="flex">
                    <span
                      className="inline-flex items-center px-4 py-3 border border-r-0 border-gray-300 rounded-l-xl text-sm text-gray-500 font-mono select-none"
                      style={{ background: '#f8f9fc' }}
                    >
                      +61
                    </span>
                    <input
                      type="tel"
                      value={phone}
                      onChange={e => {
                        const val = e.target.value.replace(/\s/g, '').replace(/^0/, '');
                        if (val === '' || /^\d*$/.test(val)) {
                          setPhone(val.slice(0, 9));
                          setPhoneOtp({ step: 'idle', code: '', error: '' });
                          setPhoneChangeToken(null);
                        }
                        if (serverFieldErrors.phone) setServerFieldErrors(p => ({ ...p, phone: undefined as any }));
                      }}
                      placeholder="432 361 875"
                      style={inpFocus}
                      className={`flex-1 px-4 py-3 border rounded-r-xl text-sm outline-none transition-all font-mono text-gray-900 placeholder:text-gray-400 focus:ring-2 focus:border-transparent ${
                        submitAttempted && fieldErrors.phone ? 'border-red-400 bg-red-50' : 'border-gray-300 hover:border-gray-400'
                      }`}
                    />
                  </div>
                  {submitAttempted && fieldErrors.phone && <p className="text-xs text-red-500 mt-1.5">{fieldErrors.phone}</p>}
                  {serverFieldErrors.phone && <p className="text-xs text-red-500 mt-1.5">{serverFieldErrors.phone}</p>}
                  {isPhoneChanging && (
                    <div className="mt-3 rounded-xl border border-blue-200 bg-blue-50/60 p-4 space-y-3">
                      {phoneOtp.step === 'idle' && (
                        <>
                          <p className="text-xs text-blue-800 leading-relaxed">
                            Your mobile number is used to sign in. We’ll verify the new number before saving it.
                          </p>
                          <button
                            type="button"
                            onClick={() => void handleSendPhoneChangeOtp()}
                            className="rounded-lg px-3 py-2 text-xs font-semibold transition-all"
                            style={{ background: GOLD, color: NAVY }}
                          >
                            Send SMS verification code
                          </button>
                          {phoneOtp.error && <p className="text-xs text-red-600">{phoneOtp.error}</p>}
                        </>
                      )}
                      {phoneOtp.step === 'sending' && <p className="text-xs text-blue-700">Sending code…</p>}
                      {(phoneOtp.step === 'sent' || phoneOtp.step === 'verifying') && (
                        <>
                          <p className="text-xs text-blue-800">Enter the code sent to {fullPhone}.</p>
                          <input
                            type="text"
                            inputMode="numeric"
                            maxLength={6}
                            value={phoneOtp.code}
                            onChange={e => setPhoneOtp(p => ({ ...p, code: e.target.value.replace(/\D/g, '') }))}
                            placeholder="000000"
                            className="w-full px-4 py-2.5 border border-blue-300 rounded-lg text-center text-lg font-mono tracking-[0.5em] outline-none focus:ring-2 bg-white"
                            style={{ '--tw-ring-color': GOLD } as React.CSSProperties}
                          />
                          {phoneOtp.error && <p className="text-xs text-red-600">{phoneOtp.error}</p>}
                          <div className="flex gap-2">
                            <button
                              type="button"
                              disabled={phoneOtp.code.length !== 6 || phoneOtp.step === 'verifying'}
                              onClick={() => void handleVerifyPhoneChangeOtp()}
                              className="rounded-lg px-3 py-2 text-xs font-semibold transition-all disabled:opacity-60"
                              style={{ background: NAVY, color: '#fff' }}
                            >
                              {phoneOtp.step === 'verifying' ? 'Verifying…' : 'Verify code'}
                            </button>
                            <button
                              type="button"
                              disabled={phoneOtp.step === 'verifying'}
                              onClick={() => void handleSendPhoneChangeOtp()}
                              className="rounded-lg px-3 py-2 text-xs font-medium text-blue-700 transition-all hover:underline disabled:opacity-50"
                            >
                              Resend
                            </button>
                          </div>
                        </>
                      )}
                      {phoneOtp.step === 'verified' && (
                        <p className="text-xs font-medium text-emerald-600">
                          ✓ New mobile number verified — it will be updated when you save.
                        </p>
                      )}
                    </div>
                  )}
                </div>

              </div>
            </Section>

            {/* ── Saved Addresses ── */}
            <Section
              icon={MapPin}
              title="Saved Addresses"
              badge={addresses.length > 0 ? `${addresses.length} Address${addresses.length !== 1 ? 'es' : ''}` : 'Optional'}
            >
              <div className="space-y-3">
                <p className="text-xs text-gray-500 -mt-2">
                  Save addresses to speed up mobile bookings.
                </p>

                {/* address cards */}
                {addresses.length > 0 && (
                  <div className="space-y-2">
                    {addresses.map((addr) => (
                      <motion.div
                        key={addr.id}
                        initial={{ opacity: 0, y: -6 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="flex items-start justify-between px-4 py-3 rounded-xl border border-gray-200"
                        style={{ background: '#f8f9fc' }}
                      >
                        <div className="flex items-start gap-3 min-w-0">
                          <span
                            className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0 mt-0.5"
                            style={{ background: NAVY_TINT }}
                          >
                            <MapPin className="w-4 h-4" style={{ color: NAVY }} />
                          </span>
                          <div className="min-w-0">
                            <div className="flex items-center gap-2">
                              <p className="text-sm font-semibold text-gray-900">{addr.label}</p>
                              {addr.is_default && (
                                <span
                                  className="text-xs px-2 py-0.5 rounded-full font-medium flex items-center gap-1"
                                  style={{ background: NAVY_TINT, color: NAVY_MID }}
                                >
                                  <Star className="w-3 h-3" />Default
                                </span>
                              )}
                            </div>
                            <p className="text-xs text-gray-500 mt-0.5 leading-relaxed">
                              {[addr.street_address, addr.suburb, [addr.state, addr.postcode].filter(Boolean).join(' ')].filter(Boolean).join(', ')}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-1 shrink-0 ml-2">
                          {!addr.is_default && (
                            <button
                              type="button"
                              title="Set as default"
                              onClick={async () => {
                                if (!session?.accessToken) return;
                                try {
                                  const updated = await apiSetDefaultAddress(session.accessToken, addr.id);
                                  setAddresses((prev) => prev.map((a) => ({ ...a, is_default: a.id === updated.id })));
                                } catch { /* ignore */ }
                              }}
                              className="p-1.5 rounded-lg text-gray-400 hover:text-yellow-500 hover:bg-yellow-50 transition-all"
                            >
                              <Star className="w-4 h-4" />
                            </button>
                          )}
                          <button
                            type="button"
                            title="Edit address"
                            onClick={() => {
                              setAddrEditId(addr.id);
                              setAddrLabel(addr.label);
                              setAddrDraft({ street_address: addr.street_address, suburb: addr.suburb, state: addr.state, postcode: addr.postcode });
                              setAddrFormOpen(true);
                              setAddrError('');
                            }}
                            className="p-1.5 rounded-lg text-gray-400 hover:text-blue-500 hover:bg-blue-50 transition-all"
                          >
                            <Pencil className="w-4 h-4" />
                          </button>
                          <button
                            type="button"
                            title="Remove address"
                            onClick={async () => {
                              if (!session?.accessToken) return;
                              try {
                                await apiDeleteAddress(session.accessToken, addr.id);
                                setAddresses((prev) => {
                                  const next = prev.filter((a) => a.id !== addr.id);
                                  // Promote first remaining to default if needed
                                  if (addr.is_default && next.length > 0 && !next.some((a) => a.is_default)) {
                                    next[0] = { ...next[0], is_default: true };
                                  }
                                  return next;
                                });
                              } catch { /* ignore */ }
                            }}
                            className="p-1.5 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 transition-all"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                )}

                {/* add / edit address form */}
                {addrFormOpen ? (
                  <div className="rounded-xl border p-4 space-y-3" style={{ background: '#f8f9fc', borderColor: NAVY_TINT }}>
                    <div>
                      <label className="block text-xs font-semibold text-gray-500 mb-1 uppercase tracking-wider">Label</label>
                      <input
                        type="text"
                        value={addrLabel}
                        onChange={(e) => setAddrLabel(e.target.value)}
                        placeholder="e.g. Home, Work"
                        style={inpFocus}
                        className={`${inp} border-gray-300 hover:border-gray-400`}
                      />
                    </div>
                    <AddressDetailsFields
                      value={addrDraft}
                      onChange={setAddrDraft}
                      focusStyle={inpFocus}
                    />
                    {addrError && <p className="text-xs text-red-500">{addrError}</p>}
                    <div className="flex items-center gap-2 pt-1">
                      <button
                        type="button"
                        disabled={addrSaving}
                        onClick={async () => {
                          if (!session?.accessToken) return;
                          if (!addrDraft.street_address.trim()) {
                            setAddrError('Street address is required.');
                            return;
                          }
                          setAddrSaving(true);
                          setAddrError('');
                          try {
                            if (addrEditId) {
                              const updated = await apiUpdateAddress(session.accessToken, addrEditId, {
                                label: addrLabel.trim() || 'Home',
                                ...addrDraft,
                              });
                              setAddresses((prev) => prev.map((a) => (a.id === addrEditId ? updated : a)));
                            } else {
                              const created = await apiCreateAddress(session.accessToken, {
                                label: addrLabel.trim() || 'Home',
                                ...addrDraft,
                                is_default: addresses.length === 0,
                              });
                              setAddresses((prev) => [...prev, created]);
                            }
                            setAddrFormOpen(false);
                            setAddrEditId(null);
                            setAddrDraft(createEmptyAddressDetails());
                            setAddrLabel('Home');
                          } catch (e) {
                            setAddrError(e instanceof Error ? e.message : 'Could not save address.');
                          } finally {
                            setAddrSaving(false);
                          }
                        }}
                        className="px-4 py-2 rounded-xl text-sm font-semibold flex items-center gap-2 transition-all disabled:opacity-60"
                        style={{ background: BTN_BG, color: BTN_TEXT, boxShadow: '0 2px 8px rgba(201,168,76,0.35)' }}
                      >
                        <Check className="w-4 h-4" />
                        {addrSaving ? 'Saving…' : addrEditId ? 'Update' : 'Save Address'}
                      </button>
                      <button
                        type="button"
                        onClick={() => {
                          setAddrFormOpen(false);
                          setAddrEditId(null);
                          setAddrDraft(createEmptyAddressDetails());
                          setAddrLabel('Home');
                          setAddrError('');
                        }}
                        className="px-4 py-2 rounded-xl text-sm font-semibold border border-gray-200 text-gray-500 hover:text-gray-700 hover:border-gray-300 transition-all bg-white"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={() => {
                      setAddrEditId(null);
                      setAddrDraft(createEmptyAddressDetails());
                      setAddrLabel('Home');
                      setAddrError('');
                      setAddrFormOpen(true);
                    }}
                    className="flex items-center gap-2 text-sm font-semibold transition-all hover:opacity-80"
                    style={{ color: NAVY }}
                  >
                    <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: NAVY_TINT }}>
                      <Plus className="w-4 h-4" style={{ color: NAVY }} />
                    </div>
                    Add an Address
                  </button>
                )}
              </div>
            </Section>

            {/* ── My Garage ── */}
            <Section
              icon={Car}
              title="Vehicles Details"
              badge={vehicles.length > 0 ? `${vehicles.length} vehicle${vehicles.length > 1 ? 's' : ''}` : undefined}
            >
              <div className="space-y-3">
                <p className="text-xs text-gray-500 -mt-2">
                  Add the vehicles you’d like us to manage, track, and service.
                </p>

                {/* saved vehicles */}
                {vehicles.length > 0 && (
                  <div className="space-y-2">
                    {vehicles.map(vehicle => (
                      <motion.div
                        key={vehicle.id}
                        initial={{ opacity: 0, y: -6 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="flex items-center justify-between px-4 py-3 rounded-xl border border-gray-200"
                        style={{ background: '#f8f9fc' }}
                      >
                        <div className="flex items-center gap-3">
                          <span
                            className="w-8 h-8 rounded-lg flex items-center justify-center shrink-0"
                            style={{ background: NAVY_TINT }}
                          >
                            <Car className="w-4 h-4" style={{ color: NAVY }} />
                          </span>
                          <div>
                            <p className="text-sm font-semibold text-gray-900">{vehicle.model}</p>
                            <p className="text-xs text-gray-500">
                              {vehicle.type} · <span className="font-mono tracking-wider">{vehicle.number}</span>
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-1 shrink-0 ml-2">
                          <button
                            type="button"
                            title="Edit vehicle"
                            onClick={() => startEditVehicle(vehicle)}
                            className="p-1.5 rounded-lg text-gray-400 hover:text-blue-500 hover:bg-blue-50 transition-all"
                          >
                            <Pencil className="w-4 h-4" />
                          </button>
                          <button
                            type="button"
                            onClick={() => removeVehicle(vehicle.id)}
                            className="p-1.5 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 transition-all"
                            aria-label="Remove vehicle"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                )}

                {/* add vehicle inline form */}
                {vehicleFormOpen ? (
                  <div
                    className="rounded-xl border p-4"
                    style={{ background: '#f8f9fc', borderColor: NAVY_TINT }}
                  >
                    <div className="flex flex-wrap md:flex-nowrap gap-3 items-end">
                      <div className="w-full md:flex-1 min-w-0">
                        <label className="block text-xs font-semibold text-gray-500 mb-1 uppercase tracking-wider">Body Style</label>
                        <select
                          value={currentVehicle.type}
                          onChange={e => setCurrentVehicle({ ...currentVehicle, type: e.target.value })}
                          style={inpFocus}
                          className={`${inp} bg-white ${!currentVehicle.type ? 'text-gray-400' : 'text-gray-900'} ${
                            vehicleAddTouched && !currentVehicle.type ? 'border-red-400' : 'border-gray-300'
                          }`}
                        >
                          <option value="">Select type</option>
                          {vehicleCatalogTypes.map(t => <option key={t} value={t}>{t}</option>)}
                        </select>
                      </div>

                      <div className="w-full md:flex-1 min-w-0">
                        <label className="block text-xs font-semibold text-gray-500 mb-1 uppercase tracking-wider">Make &amp; Model</label>
                        <input
                          type="text"
                          value={currentVehicle.model}
                          onChange={e => setCurrentVehicle({ ...currentVehicle, model: e.target.value })}
                          placeholder="e.g. BMW X5"
                          style={inpFocus}
                          className={`${inp} ${
                            vehicleAddTouched && !currentVehicle.model?.trim() ? 'border-red-400' : 'border-gray-300'
                          }`}
                        />
                      </div>

                      <div className="w-full md:flex-1 min-w-0">
                        <label className="block text-xs font-semibold text-gray-500 mb-1 uppercase tracking-wider">Registration</label>
                        <input
                          type="text"
                          value={currentVehicle.number}
                          onChange={e => {
                            const val = e.target.value.toUpperCase();
                            if (val === '' || /^[A-Z0-9]*$/.test(val))
                              setCurrentVehicle({ ...currentVehicle, number: val });
                          }}
                          placeholder="e.g. ABC1234"
                          style={inpFocus}
                          className={`${inp} font-mono ${
                            vehicleAddTouched && (!currentVehicle.number || !/^[A-Z0-9]{2,7}$/.test(currentVehicle.number))
                              ? 'border-red-400' : 'border-gray-300'
                          }`}
                        />
                      </div>

                      {/* save + cancel — same row */}
                      <div className="flex items-end gap-2 shrink-0">
                        <button
                          type="button"
                          onClick={handleSaveVehicleClick}
                          title={vehicleEditId ? 'Update vehicle' : 'Save vehicle'}
                          className="w-10 h-[46px] rounded-xl flex items-center justify-center transition-all hover:brightness-105 shrink-0"
                          style={{ background: BTN_BG, color: BTN_TEXT, boxShadow: '0 2px 8px rgba(201,168,76,0.35)' }}
                        >
                          <Check className="w-5 h-5" strokeWidth={2.5} />
                        </button>
                        <button
                          type="button"
                          onClick={closeVehicleForm}
                          title="Cancel"
                          className="w-10 h-[46px] rounded-xl flex items-center justify-center border border-gray-200 text-gray-400 hover:text-gray-600 hover:border-gray-300 transition-all shrink-0 bg-white"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    {vehicleAddTouched && (
                      <p className="text-xs text-red-500 mt-2">
                        Please fill in all three fields to {vehicleEditId ? 'update' : 'add'} a vehicle.
                      </p>
                    )}
                  </div>
                ) : (
                  <button
                    type="button"
                    onClick={() => {
                      setVehicleEditId(null);
                      setCurrentVehicle({ type: '', number: '', model: '' });
                      setVehicleFormOpen(true);
                      setVehicleAddTouched(false);
                    }}
                    className="flex items-center gap-2 text-sm font-semibold transition-all hover:opacity-80"
                    style={{ color: NAVY }}
                  >
                    <div
                      className="w-7 h-7 rounded-lg flex items-center justify-center"
                      style={{ background: NAVY_TINT }}
                    >
                      <Plus className="w-4 h-4" style={{ color: NAVY }} />
                    </div>
                    Add a Vehicle
                  </button>
                )}
              </div>
            </Section>

            {/* error */}
            {error && (
              <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 flex items-start gap-2">
                <span className="shrink-0 mt-0.5">⚠</span>
                <span>{error}</span>
              </div>
            )}

            {/* saved confirmation */}
            {saved && (
              <motion.div
                initial={{ opacity: 0, y: -6 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700 flex items-center gap-2"
              >
                <Check className="w-4 h-4 shrink-0" />
                <span>Profile saved successfully.</span>
              </motion.div>
            )}

            {/* submit */}
            <button
              type="submit"
              disabled={loading || !hydrated}
              className="w-full py-4 rounded-xl font-semibold text-sm transition-all disabled:opacity-60 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              style={{
                background: BTN_BG,
                color: BTN_TEXT,
                boxShadow: loading ? 'none' : '0 4px 14px rgba(201,168,76,0.4)',
              }}
            >
              {loading ? (
                <svg className="animate-spin w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                </svg>
              ) : saved ? (
                <><Check className="w-4 h-4" />Saved</>
              ) : (
                <><Save className="w-4 h-4" />Save Changes</>
              )}
            </button>

          </form>
        </motion.div>
      </div>
    </div>
  );
}
